server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
    context-path: /api/v1

spring:
  application:
    name: Glim
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glimdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  profiles:
    include: dev, secret

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: none

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true
